package app.chronota.ui.components

object AppIcons {
    val Person get() = CategoryIconLibrary.image("user-round")
    val Clock get() = CategoryIconLibrary.image("clock")
    val Bell get() = CategoryIconLibrary.image("bell")
    val Edit get() = CategoryIconLibrary.image("pencil")
    val Check get() = CategoryIconLibrary.image("check")
    val Link get() = CategoryIconLibrary.image("link")
    val Down get() = CategoryIconLibrary.image("chevron-down")
    val Palette get() = CategoryIconLibrary.image("palette")
    val Delete get() = CategoryIconLibrary.image("trash")
    val Add get() = CategoryIconLibrary.image("plus")
    val Close get() = CategoryIconLibrary.image("x")
    val Play get() = CategoryIconLibrary.image("play")
    val Pause get() = CategoryIconLibrary.image("pause")
    val Stop get() = CategoryIconLibrary.image("square")
    val Previous get() = CategoryIconLibrary.image("chevron-left")
    val Next get() = CategoryIconLibrary.image("chevron-right")
    val Book get() = CategoryIconLibrary.image("book-open")
    val Code get() = CategoryIconLibrary.image("code-xml")
    val Coffee get() = CategoryIconLibrary.image("coffee")
    val Star get() = CategoryIconLibrary.image("star")
    val Work get() = CategoryIconLibrary.image("briefcase-business")
    val Music get() = CategoryIconLibrary.image("music")
    val Today get() = CategoryIconLibrary.image("calendar-days")
    /** The orb's "new plan" action: a checklist, so it does not read as the Today tab's calendar. */
    val Plan get() = CategoryIconLibrary.image("clipboard-list")
    /** The Records page and its "new record" action: a film strip, for what was recorded. */
    val Record get() = CategoryIconLibrary.image("film")
    val Todo get() = CategoryIconLibrary.image("list-todo")
    /** Statistics, which live inside the Records page. */
    val Chart get() = CategoryIconLibrary.image("chart-no-axes-combined")
    val Settings get() = CategoryIconLibrary.image("settings-2")
    /** Opening Settings from a page header. Distinct from [Settings], which means "show details". */
    val Wrench get() = CategoryIconLibrary.image("wrench")
    val Orbit get() = CategoryIconLibrary.image("orbit")
    val Categories get() = CategoryIconLibrary.image("folder-open")
    val Back get() = CategoryIconLibrary.image("arrow-left")
    val Home get() = CategoryIconLibrary.image("house")
    val Heart get() = CategoryIconLibrary.image("heart")
    val Sport get() = CategoryIconLibrary.image("dumbbell")
    val Food get() = CategoryIconLibrary.image("utensils")
    val Travel get() = CategoryIconLibrary.image("plane")
    val Camera get() = CategoryIconLibrary.image("camera")
    val Game get() = CategoryIconLibrary.image("gamepad-2")
    val Plant get() = CategoryIconLibrary.image("sprout")
    val Lab get() = CategoryIconLibrary.image("flask-conical")
    val Chat get() = CategoryIconLibrary.image("chat")
    val Repeat get() = CategoryIconLibrary.image("repeat")
    val Sort get() = CategoryIconLibrary.image("sort-descending")
    val Timer get() = CategoryIconLibrary.image("timer")
    val Sunrise get() = CategoryIconLibrary.image("sunrise")
    val FileText get() = CategoryIconLibrary.image("file-text")
    val Notebook get() = CategoryIconLibrary.image("notebook")
    /** The WebDAV backup: a copy kept off the device. */
    val Cloud get() = CategoryIconLibrary.image("cloud")
    /** Writing a backup out to a file, and reading one back in. */
    val Export get() = CategoryIconLibrary.image("upload")
    val Import get() = CategoryIconLibrary.image("download")
    val Earth get() = CategoryIconLibrary.image("earth")
    val Alarm get() = CategoryIconLibrary.image("alarm-clock")
    val Target get() = CategoryIconLibrary.image("target")
    val Grip get() = CategoryIconLibrary.image("grip")
    val WeekStart get() = CategoryIconLibrary.image("sun")
}
